# -*- coding: utf-8 -*-
"""Dashboard em Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1159j7wD0cBoueAJEd4e2d3969PeJsziv
"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

# Salvar o DataFrame como um arquivo CSV
dados = pd.read_csv('/content/dados_vendas.csv')

dados.head()

import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go

# Carregar os dados de vendas
dados_vendas = pd.read_csv('dados_vendas.csv')

# Análise exploratória dos dados
total_vendas = dados_vendas['Valor'].sum()
vendas_por_produto = dados_vendas.groupby('Produto')['Valor'].sum().reset_index()

# Gráfico de barras com as vendas por produto usando Matplotlib
plt.figure(figsize=(25, 10))
plt.bar(vendas_por_produto['Produto'], vendas_por_produto['Valor'])
plt.xlabel('Produto')
plt.ylabel('Total de Vendas')
plt.title('Vendas por Produto')
plt.xticks(rotation=45)
plt.show()

# Gráfico de pizza com as vendas por produto usando Plotly
fig = go.Figure(data=[go.Pie(labels=vendas_por_produto['Produto'],
                             values=vendas_por_produto['Valor'])])
fig.update_layout(title='Vendas por Produto')
fig.show()

# Exibir o total de vendas
print('Total de Vendas: $', total_vendas)

